Уведомление УДЯ об изменении состояний устройств (облегченная версия)
dmitry-k/yandex_smart_home pull request #164
Opened 2021-03-24 10:07 UTC by glebsterx

Согласно [документации](https://yandex.ru/dev/dialogs/alice/doc/smart-home/reference-alerts/post-skill_id-callback-state.html) данной модификацией отсылается запрос об изменении состояния устройств по событию state_changed. Все лишние такие события фильтруются согласно конфигурации компонента.
Для отправки запросов нужен [OAuth-токен](https://oauth.yandex.ru/authorize?response_type=token&client_id=c473ca268cd749d3a8371351a8f2bcbd), ID навыка в [диалогах](https://dialogs.yandex.ru/developer) и ID пользователя Home Assistant под которым выполнена связка аккаунтов (Настройки - Пользователи).
Эта модификация решает вопрос заданный тут: #141.
Для чего? Когда (если) в УДЯ появятся триггеры в сценариях - можно будет использовать датчики, не открывая квазар и не проваливаясь в устройство, чтобы узнать его состояние, как это происходит сейчас. А пока что это все дает синхронизацию, например, статуса светильников и прочих устройств.

2021-04-10 11:22 UTC, dmitry-k requested changes
Извиняюсь что долго не мог посмотреть PR.

---

При первом запуске без каких-либо настроек:

```
2021-04-10 17:21:44 ERROR (MainThread) [custom_components.yandex_smart_home] Skill Setup error
Traceback (most recent call last):
  File "/home/ha/.homeassistant/custom_components/yandex_smart_home/__init__.py", line 92, in _setup_skill
    skill = YandexSkillLight(hass, config)
  File "/home/ha/.homeassistant/custom_components/yandex_smart_home/skill.py", line 30, in __init__
    self.oauth_token = config[CONF_SKILL][CONF_SKILL_OAUTH_TOKEN]
KeyError: 'oauth_token'
```

Параметры опциональные, не должно быть ошибок.

Ну и в целом не понятно как это должно работать. Настроил, включаю-выключаю лампочку в HA, запросы идут, никаких ошибок, ответ 202, 'status': 'ok', в яндексе ничего не меняется.
Если это нормально, то хочется более подробного описания в README.

2021-04-13 14:00 UTC, glebsterx commented
@dmitry-k, я переименовал файл, класс, константы и переменные и кое-что переделал, чтобы в будущем не путаться.. Протестировал насколько это возможно было.

2021-04-18 10:14 UTC, merged

2021-04-18 10:14 UTC, dmitry-k commented
NOTIFIER_ENABLED лежащий в конфиге выглядит несколько костыльно. Это не конфиг и этот флаг должен просто храниться в переменной где-то, но для начала пойдёт и так.
В остальном неплохо, спасибо.

2021-04-18 10:31 UTC, glebsterx commented
Спасибо и Вам =) Я лучше не придумал где его хранить.. Но по идее hass.data[DOMAIN] - массив в который в данный момент хранит конфиг и эту переменную.. Но выглядит не супер, согласен. Зато работает =)